### ISSUE TITLE
can't get it work anymore

### ISSUE THREAD

**Issue by takiainen** [aajanki/yle-dl#353]
Earlier this year I used yle-dl successfully without problems, but now even after update it gives me errors:

puu@kaarna:~$ yle-dl https://yle.fi/aihe/artikkeli/2017/04/13/kevataamun-laulajia-punarinta
Traceback (most recent call last):
  File "/home/puu/.local/bin/yle-dl", line 8, in <module>
    sys.exit(main())
  File "/home/puu/.local/lib/python3.8/site-packages/yledl/yledl.py", line 432, in main
    fstype = get_filesystem_type(destdir).upper()
  File "/home/puu/.local/lib/python3.8/site-packages/yledl/io.py", line 190, in get_filesystem_type
    if Path(dir).is_relative_to(Path(p.mountpoint)):
AttributeError: 'PosixPath' object has no attribute 'is_relative_to'

Or something from YLE areena: 

puu@kaarna:~$ yle-dl https://areena.yle.fi/1-50830195
Traceback (most recent call last):
  File "/home/puu/.local/bin/yle-dl", line 8, in <module>
    sys.exit(main())
  File "/home/puu/.local/lib/python3.8/site-packages/yledl/yledl.py", line 432, in main
    fstype = get_filesystem_type(destdir).upper()
  File "/home/puu/.local/lib/python3.8/site-packages/yledl/io.py", line 190, in get_filesystem_type
    if Path(dir).is_relative_to(Path(p.mountpoint)):
AttributeError: 'PosixPath' object has no attribute 'is_relative_to'

Running this on Linux Mint 20.

Any idea where's the problem?

**Comment by Jormangeud** [comment]
If you cannot update your python3 to 3.9 or above, you could try the patch

**Comment by aajanki** [comment]
I had apparently broken support for Python 3.8 in an earlier release. @Jormangeud's patch should indeed fix it. I merged the patch to the master branch.

@takiainen, you can either update to the latest development version (master branch from Github) or temporarily downgrade to version 20230611, which is the latest version that still worked on Python 3.8, and update to the latest version once I make a new release at some point in the future.
